#!/bin/bash

_escape () {
        if [ "$1" ]; then
                printf %s "$1" | _umpdc_escape
        else
                sed -r 's/([][(){}<>=;:'\''"\$*|&!?\ ])/\\\1/g'
        fi
}

_smpd() 
{
    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
    cur1=${cur//\./\\\.}
    IFS=$'\n'

    case "${COMP_WORDS[1]}" in
	\-x)
		local words=$(kpmpd -0)
		COMPREPLY=( $( grep -i "^${cur1}" <(printf %s\\n "${words}") 2>/dev/null | _escape ) )
		return 0
	;;
	\-a)
        local words=$(kpmpd -0)
        COMPREPLY=( $( grep -i "^${cur1}" <(printf %s\\n "${words}") 2>/dev/null | _escape ) )
        return 0
	;;

	*)
	;;
    esac
}

complete -F _smpd smpd
